### PR TITLE
Fixes to the Haskell runners

### PR DESCRIPTION
**Pull request by doyougnu**
Hey there I've done some more thorough testing and fixed some issues in the HS backend.

This time I've also slightly updated the README to point to the book I'm writing with the Haskell Foundation. That URL is going to be out of date fairly soon because we're moving the repo but I'll submit a PR to update when we do to keep everything aligned.

### CODE REVIEW

**Comment by doyougnu** [comment]
Hey there! I've added way more docs on how to use the Haskell runner to the readme, complete with `imgur` linked images of the output and a breakdown of the flags that were added. This PR should be ready for review now. There is absolutely no rush from my side so please don't feel pressured.

**Comment by yongrenjie** [comment]
Hi! Thanks again for sending this upstream. 😄 

Quick question re. the examples in the docs: is there a case where the `:context:` flag make a difference for you? I think it shouldn't have any impact on the Haskell code execution. The only situation I can imagine where you'd need to set it for a non-Python code block would be if you were interspersing Python blocks with other languages and wanted to preserve variables between the Python blocks.

Not really a huge issue at all; I'm happy to merge and then edit the README according to your reply.

**Comment by doyougnu** [comment]
No as far as I can tell it makes no difference. Perhaps this is something to add to the README?

**Comment by yongrenjie** [comment]
Alright! I was just curious because the examples you added had the `context` flag and I wasn't sure if I was missing something.

Yes, I think the readme deserves to be split up too (or turned into its own Sphinx doc); I'll work on it one of these days.

**Pull request merged**
